---

- assert:
    that:
      - rabbitmq_cluster_name is defined
      - rabbitmq_cluster_name | length > 0

- name: Get cluster name from API
  uri:
    url: http://127.0.0.1:15672/api/cluster-name
    user: "{{ rabbitmq_management_user.name }}"
    password: "{{ rabbitmq_management_user.password }}"
    return_content: yes
  register: register_rabbitmqctl_api_cluster_name
  changed_when: false

- assert:
    that:
      - "'content' in register_rabbitmqctl_api_cluster_name"
      - register_rabbitmqctl_api_cluster_name.content is defined
      - "'name' in (register_rabbitmqctl_api_cluster_name.content | from_json)"
      - (register_rabbitmqctl_api_cluster_name.content | from_json).name | length > 0

- block:
  # this block is executed only on the first node listed in
  # rabbitmq_cluster_nodes
  #
  # XXX the first node must be the first node to start because the rest of the
  # nodes join to the first node
  - name: Set cluster name
    command: "rabbitmqctl set_cluster_name {{ rabbitmq_cluster_name | quote }}"
    register: register_set_cluster_name

  - name: Get cluster name from API again
    uri:
      url: http://127.0.0.1:15672/api/cluster-name
      user: "{{ rabbitmq_management_user.name }}"
      password: "{{ rabbitmq_management_user.password }}"
      return_content: yes
    register: register_rabbitmqctl_api_cluster_name_again
    changed_when: false

  - assert:
      that:
        - "'content' in register_rabbitmqctl_api_cluster_name_again"
        - register_rabbitmqctl_api_cluster_name_again.content is defined
        - "'name' in (register_rabbitmqctl_api_cluster_name_again.content | from_json)"
        - (register_rabbitmqctl_api_cluster_name_again.content | from_json).name | length > 0
        - (register_rabbitmqctl_api_cluster_name_again.content | from_json).name == rabbitmq_cluster_name
  when:
    - rabbitmq_cluster_nodes[0] == ansible_fqdn
    - not (register_rabbitmqctl_api_cluster_name.content | from_json).name == rabbitmq_cluster_name

- block:
  # this block is executed on the rest of nodes listed in
  # rabbitmq_cluster_nodes
  #
  # XXX the block cannot be tested in unit test
  - name: Stop rabbitmq app
    command: rabbitmqctl stop_app

  - name: Join to cluster
    shell: "rabbitmqctl join_cluster 'rabbit@{{ rabbitmq_cluster_nodes[0] }}'"

  - name: Start rabbitmq app
    command: rabbitmqctl start_app

  - name: Get cluster name from API again
    uri:
      url: http://127.0.0.1:15672/api/cluster-name
      user: "{{ rabbitmq_management_user.name }}"
      password: "{{ rabbitmq_management_user.password }}"
      return_content: yes
    register: register_rabbitmqctl_api_cluster_name_again
    changed_when: false

  - assert:
      that:
        - "'content' in register_rabbitmqctl_api_cluster_name_again"
        - register_rabbitmqctl_api_cluster_name_again.content is defined
        - "'name' in (register_rabbitmqctl_api_cluster_name_again.content | from_json)"
        - (register_rabbitmqctl_api_cluster_name_again.content | from_json).name | length > 0
        - (register_rabbitmqctl_api_cluster_name_again.content | from_json).name == rabbitmq_cluster_name

  when:
    - not rabbitmq_cluster_nodes[0] == ansible_fqdn
    - not (register_rabbitmqctl_api_cluster_name.content | from_json).name == rabbitmq_cluster_name
