---
# tasks file for ansible-role-rabbitmq

- include_vars: "{{ ansible_os_family }}.yml"

- set_fact:
    rabbitmq_flags_merged: "{{ rabbitmq_flags_default | combine(rabbitmq_flags) }}"

- include: "install-{{ ansible_os_family }}.yml"

- include: "configure-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ rabbitmq_log_dir }}"
    mode: 0755
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"
    state: directory

- name: Create db directory
  file:
    path: "{{ rabbitmq_db_dir }}"
    mode: 0755
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"
    state: directory

- include: cookie.yml

- name: Create rabbitmq config dir
  file:
    state: directory
    path: "{{ rabbitmq_conf_dir }}"
    mode: 0755
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"

- name: Create rabbitmq.conf
  template:
    src: rabbitmq.config.j2
    dest: "{{ rabbitmq_conf }}"
  notify: Restart rabbitmq

- name: Create rabbitmq-env.conf
  template:
    src: rabbitmq-env.conf.j2
    dest: "{{ rabbitmq_env_conf }}"
    validate: sh -n %s
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"
  notify: Restart rabbitmq

- name: Start rabbitmq
  service:
    name: "{{ rabbitmq_service }}"
    enabled: true
    state: started

- include: plugins.yml

- name: Create vhosts
  rabbitmq_vhost:
    name: "{{ item }}"
    state: present
  with_items: "{{ rabbitmq_vhosts }}"

- name: Create or remove users
  rabbitmq_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ item.state }}"
    vhost: "{{ item.vhost }}"
    tags: "administrator"
  with_items: "{{ rabbitmq_users }}"
