---

- name: Get plugins_dir from rabbitmqctl environment
  # XXX the python one-liner is to normalize output of rabbitmqctl. the output
  # differs under unknown (to me) conditions. sed(1) is tricky in this task as
  # you cannot use `\n`.
  # TODO the proper way to parse the output is to pipe it to erl, eval it, and
  # print the value of plugins_dir.
  shell: "rabbitmqctl environment | python -c \"import sys; import re; sys.stdout.write(re.sub('{plugins_dir,\\n', '{plugins_dir,', sys.stdin.read()))\" | grep plugins_dir | grep -oE '\"/.+\"' | cut -d ':' -f 2 | tr -d '\"'"
  register: register_rabbitmqctl_environment_plugins_dir
  changed_when: false

- set_fact:
    rabbitmq_plugins_dir: "{{ register_rabbitmqctl_environment_plugins_dir.stdout }}"

- name: Get stat of rabbitmq_plugins_dir
  stat:
    path: "{{ rabbitmq_plugins_dir }}"
  register: register_rabbitmq_plugins_dir_stat

- name: Assert rabbitmq_plugins_dir is directory
  assert:
    that: register_rabbitmq_plugins_dir_stat.stat.isdir

- name: Copy plugins to `plugins` directory from _local_ rabbitmq_plugins_local_src_dir
  # XXX this task is not tested in serverspec, but in integration test
  copy:
    src: "{{ rabbitmq_plugins_local_src_dir }}/"
    dest: "{{ rabbitmq_plugins_dir }}"
  when:
    - rabbitmq_plugins_local_src_dir is defined
    - rabbitmq_plugins_local_src_dir | length() > 0

- name: Enable plugins
  rabbitmq_plugin:
    names: "{{ rabbitmq_plugins | join(',') }}"

- name: Get list of enabled plugins
  shell: "rabbitmq-plugins -E list | grep -E '^\\[' | cut -f 2 -d ' '"
  register: register_rabbitmq_plugins_list_e
  changed_when: false

- name: Assert rabbitmq_plugins are enabled
  assert:
    that:
      - item in register_rabbitmq_plugins_list_e.stdout_lines
  with_items: "{{ rabbitmq_plugins }}"
  when:
    - rabbitmq_plugins | length > 0
